version: '3.3'
services:
  app:
    image: 10.100.2.10:5000/gitlab-arm:latest
    # image: fabian1233/gitlab-arm:latest
    environment:
      - HOSTNAME: gitlab.fschneider.at
      - REDIS_SERVER: enable
    ports:
      - 20022:22
    volumes:
     - gitlab-data:/var/opt/gitlab
     - gitlab-logs:/var/log/gitlab
     - gitlab-config:/etc/gitlab
    networks:
     - net
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: "redis:alpine"
    command: redis-server

    volumes:
     - redis-data:/var/lib/redis
     - redis-conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    networks:
     - net
  
networks:
  net:
    driver: overlay
#  proxy:
#    external: true

volumes:
  gitlab-data:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/data
      o: bind
      type: none

  gitlab-logs:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/logs
      o: bind
      type: none

  gitlab-config:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/config
      o: bind
      type: none

  redis-conf:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/redis.conf
      o: bind
      type: none


  redis-data:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/redis
      o: bind
      type: none
