version: '3.3'
services:
  app:
    image: 10.100.2.10:5000/gitlab-arm:latest
    # image: fabian1233/gitlab-arm:latest
    environment:
      - "HOSTNAME=https://gitlab.fschneider.at"
      - REDIS_SERVER=enable
      - POSTGRES_SERVER=enable
    ports:
      - 20022:22
    volumes:
     - gitlab-data:/var/opt/gitlab
     - gitlab-logs:/var/log/gitlab
     - gitlab-config:/etc/gitlab
    networks:
     - net
     - proxy
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.gitlab.entrypoints: web-secured
        traefik.http.routers.gitlab.rule: Host(`gitlab.fschneider.at`)
        traefik.http.routers.gitlab.tls.certresolver: mytlschallenge
        traefik.http.services.gitlab.loadbalancer.server.port: '443'
        traefik.http.services.gitlab.loadbalancer.server.scheme: https
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes

    volumes:
      - redis-data:/var/lib/redis
      - redis-backup:/data
    # - redis-conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - net

  postgres:
    image: "postgres"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: Start2020
    
    networks:
      - net

  runner:
    image: gitlab/gitlab-runner
    #replica: 3
    
    networks:
      - net
  
networks:
  net:
    driver: overlay
  proxy:
    external: true


volumes:
  gitlab-data:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/data
      o: bind
      type: none

  gitlab-logs:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/logs
      o: bind
      type: none

  gitlab-config:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/config
      o: bind
      type: none

  redis-conf:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/redis.conf
      o: bind
      type: none


  redis-data:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/redis
      o: bind
      type: none

  redis-backup:                              
    driver: local                          
    driver_opts:                           
      device: /nfsdata/volumes/gitlab/redis-backup
      o: bind                              
      type: none                           
                                           
  postgres-data:
    driver: local
    driver_opts:
      device: /nfsdata/volumes/gitlab/postgres
      o: bind
      type: none
